version: '3.8'
services:
  dev-db:
    image: postgres:14
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  pg-admin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: xyz@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - dev-db
